import { InsertSubmission } from "@shared/schema";

export const enhancedAIToolsData: InsertSubmission[] = [
  // AI Workflow Automation & Productivity
  {
    name: "FlowForma Process Automation",
    shortDescription: "AI-powered Copilot builds business processes in minutes using natural language",
    detailedDescription: "Revolutionary no-code workflow automation platform with AI Copilot that creates complex business processes 10x faster than traditional tools. Features drag-and-drop interface, natural language process creation, and enterprise-grade security for construction, healthcare, energy, and finance industries.",
    url: "https://www.flowforma.com",
    category: "ai-automation",
    pricing: "enterprise",
    rating: "4.6",
    reviewCount: 340,
    tags: ["workflow", "automation", "no-code", "enterprise", "copilot"],
    contactEmail: "contact@flowforma.com",
    featured: false,
    status: "approved"
  },
  {
    name: "Lindy AI",
    shortDescription: "Custom AI agents (Lindies) for specific business workflows and automation",
    detailedDescription: "Y Combinator-backed platform for creating custom AI agents that handle meeting prep, email triage, podcast-to-blog conversion, and other business workflows. No-code platform with strong momentum in the AI automation space.",
    url: "https://lindy.ai",
    category: "ai-automation",
    pricing: "subscription",
    rating: "4.4",
    reviewCount: 180,
    tags: ["ai-agents", "automation", "y-combinator", "no-code", "workflows"],
    contactEmail: "contact@lindy.ai",
    featured: false,
    status: "approved"
  },
  {
    name: "Relay",
    shortDescription: "Modern Zapier alternative with AI-powered workflow optimization",
    detailedDescription: "Streamlined automation platform with familiar trigger/action interface enhanced by modern AI capabilities. Features minimal learning curve, smart workflow optimization, and seamless integration with existing business applications.",
    url: "https://relay.app",
    category: "ai-automation",
    pricing: "freemium",
    rating: "4.3",
    reviewCount: 210,
    tags: ["automation", "zapier-alternative", "workflows", "integration", "ai-optimization"],
    contactEmail: "contact@relay.app",
    featured: false,
    status: "approved"
  },
  {
    name: "VectorShift",
    shortDescription: "Multi-LLM platform for complex workflows with voicebots and ML integration",
    detailedDescription: "Advanced automation platform supporting multiple LLMs for sophisticated AI workflows. Features unique voicebot capabilities, advanced machine learning integration, and codeless automation for enterprise teams needing complex AI solutions.",
    url: "https://vectorshift.ai",
    category: "ai-automation",
    pricing: "enterprise",
    rating: "4.5",
    reviewCount: 95,
    tags: ["multi-llm", "voicebots", "machine-learning", "enterprise", "complex-workflows"],
    contactEmail: "contact@vectorshift.ai",
    featured: false,
    status: "approved"
  },
  {
    name: "tl;dv",
    shortDescription: "AI meeting assistant that turns meetings into snappy reads with transcription",
    detailedDescription: "Intelligent meeting assistant that provides AI transcription, automatically creates meeting summaries, and generates shareable clips. Transforms lengthy meetings into digestible insights and actionable takeaways.",
    url: "https://tldv.io",
    category: "productivity",
    pricing: "freemium",
    rating: "4.7",
    reviewCount: 450,
    tags: ["meetings", "transcription", "summaries", "clips", "productivity"],
    contactEmail: "contact@tldv.io",
    featured: false,
    status: "approved"
  },
  {
    name: "Scribe",
    shortDescription: "AI-powered process documentation that saves 35 hours per month",
    detailedDescription: "Revolutionary process documentation tool that automatically captures and documents workflows. Uses AI to create step-by-step guides, training materials, and process documentation, saving teams significant time on manual documentation tasks.",
    url: "https://scribehow.com",
    category: "productivity",
    pricing: "freemium",
    rating: "4.8",
    reviewCount: 520,
    tags: ["documentation", "process-capture", "training", "automation", "workflow"],
    contactEmail: "contact@scribehow.com",
    featured: true,
    status: "approved"
  },

  // AI Video Generation & Editing
  {
    name: "RunwayML Gen-4",
    shortDescription: "Next-generation AI video creation with Act-One character animation",
    detailedDescription: "Leading AI video platform with Gen-4 model featuring enhanced narrative capabilities, groundbreaking Act-One character animation, real-time collaboration, and text-to-video generation. Professional-grade tool for filmmakers and content creators.",
    url: "https://runwayml.com",
    category: "ai-video-tools",
    pricing: "subscription",
    rating: "4.6",
    reviewCount: 890,
    tags: ["video-generation", "character-animation", "text-to-video", "professional", "filmmaking"],
    contactEmail: "contact@runwayml.com",
    featured: true,
    sponsoredLevel: "gold",
    sponsorshipStartDate: new Date("2025-01-01"),
    sponsorshipEndDate: new Date("2025-06-30"),
    status: "approved"
  },
  {
    name: "Pika Labs 2.2",
    shortDescription: "Democratizing video creation with 1080p HD AI video generation",
    detailedDescription: "Advanced AI video generator with Pika 2.2 supporting 1080p HD output, Pikaframes keyframe system, Pikaswaps video inpainting, and Pikadditions for inserting characters. Designed for accessibility with intuitive interface for creators of all skill levels.",
    url: "https://pika.art",
    category: "ai-video-tools",
    pricing: "freemium",
    rating: "4.4",
    reviewCount: 670,
    tags: ["video-generation", "hd-output", "video-inpainting", "accessible", "social-media"],
    contactEmail: "contact@pika.art",
    featured: false,
    status: "approved"
  },
  {
    name: "Synthesia 2025",
    shortDescription: "AI avatar videos with multilingual text-to-video technology",
    detailedDescription: "Enterprise-grade AI video generation platform creating professional avatar videos from text. Features multilingual support, realistic AI avatars, brand customization, and integration capabilities for business communications and training.",
    url: "https://synthesia.io",
    category: "ai-video-tools",
    pricing: "subscription",
    rating: "4.5",
    reviewCount: 1200,
    tags: ["avatar-videos", "multilingual", "enterprise", "business-communication", "training"],
    contactEmail: "contact@synthesia.io",
    featured: false,
    status: "approved"
  },
  {
    name: "Crayo AI",
    shortDescription: "TikTok-style short-form video creation with AI voiceovers and effects",
    detailedDescription: "Specialized AI tool for creating viral short-form videos optimized for TikTok, Instagram Reels, and YouTube Shorts. Features AI voiceovers, automated effects, trending templates, and viral content optimization.",
    url: "https://crayo.ai",
    category: "ai-video-tools",
    pricing: "freemium",
    rating: "4.2",
    reviewCount: 280,
    tags: ["short-form", "tiktok", "viral-content", "voiceovers", "social-media"],
    contactEmail: "contact@crayo.ai",
    featured: false,
    status: "approved"
  },

  // AI Code Assistants & Developer Tools
  {
    name: "Cursor Pro",
    shortDescription: "AI-powered code editor with project-wide context and multi-file editing",
    detailedDescription: "Revolutionary AI code editor with Composer mode, entire project context awareness, multiple AI models (GPT-4o, Claude 3.5 Sonnet, Gemini 2.0), and 320ms autocomplete response time. Leading innovation in multi-file editing and project scaffolding.",
    url: "https://cursor.sh",
    category: "ai-code-assistants",
    pricing: "subscription",
    rating: "4.8",
    reviewCount: 950,
    tags: ["code-editor", "project-context", "multi-model", "fast-autocomplete", "developer-tools"],
    contactEmail: "contact@cursor.sh",
    featured: true,
    status: "approved"
  },
  {
    name: "GitHub Copilot Enterprise",
    shortDescription: "AI pair programmer with native IDE integration and team workflows",
    detailedDescription: "Enterprise-grade AI coding assistant with native VS Code integration, multi-model support (GPT-4o, Claude 3.5 Sonnet, o1), agent mode, and comprehensive GitHub ecosystem integration. Industry standard for AI-assisted development.",
    url: "https://github.com/features/copilot",
    category: "ai-code-assistants",
    pricing: "enterprise",
    rating: "4.7",
    reviewCount: 2100,
    tags: ["github", "ide-integration", "enterprise", "pair-programming", "multi-model"],
    contactEmail: "contact@github.com",
    featured: false,
    status: "approved"
  },
  {
    name: "Qodo",
    shortDescription: "AI-powered automated unit test generation and code quality optimization",
    detailedDescription: "Specialized AI tool focused on automated unit test generation, code quality analysis, and testing optimization. Helps developers maintain high code quality standards with intelligent test creation and quality metrics.",
    url: "https://qodo.ai",
    category: "ai-code-assistants",
    pricing: "freemium",
    rating: "4.4",
    reviewCount: 180,
    tags: ["unit-testing", "code-quality", "automated-testing", "developer-tools", "quality-metrics"],
    contactEmail: "contact@qodo.ai",
    featured: false,
    status: "approved"
  },
  {
    name: "Amazon Q Developer",
    shortDescription: "AWS-native AI coding assistant with cloud development focus",
    detailedDescription: "Cloud-native AI development assistant optimized for AWS environments. Features multi-agent workflows, AWS service integration, cloud architecture guidance, and specialized tools for serverless and cloud-native development.",
    url: "https://aws.amazon.com/q/developer",
    category: "ai-code-assistants",
    pricing: "freemium",
    rating: "4.3",
    reviewCount: 320,
    tags: ["aws", "cloud-development", "serverless", "multi-agent", "cloud-native"],
    contactEmail: "contact@aws.amazon.com",
    featured: false,
    status: "approved"
  },
  {
    name: "Aider",
    shortDescription: "Terminal-based AI coding assistant with git integration and local models",
    detailedDescription: "CLI-first AI coding assistant designed for terminal workflows. Features seamless git integration, support for local models, pair programming in the command line, and optimization for developers who prefer terminal-based workflows.",
    url: "https://aider.chat",
    category: "ai-code-assistants",
    pricing: "open-source",
    rating: "4.5",
    reviewCount: 150,
    tags: ["terminal", "cli", "git-integration", "local-models", "open-source"],
    contactEmail: "contact@aider.chat",
    featured: false,
    status: "approved"
  },

  // AI Marketing & Social Media Tools
  {
    name: "Sprout Social AI",
    shortDescription: "AI-powered social media management with content generation and analytics",
    detailedDescription: "Comprehensive social media platform with AI-powered content generation, social listening, advanced analytics, and CRM integration. Features unified inbox, campaign management, and team collaboration tools for enterprise social media management.",
    url: "https://sproutsocial.com",
    category: "ai-marketing",
    pricing: "subscription",
    rating: "4.6",
    reviewCount: 850,
    tags: ["social-media", "content-generation", "analytics", "crm", "enterprise"],
    contactEmail: "contact@sproutsocial.com",
    featured: false,
    status: "approved"
  },
  {
    name: "Jasper AI",
    shortDescription: "AI content creation platform for blog posts, ad copy, and marketing materials",
    detailedDescription: "Leading AI writing assistant specialized in marketing content creation. Features brand voice training, template library, SEO optimization, team collaboration, and integration with marketing workflows for consistent, high-quality content at scale.",
    url: "https://jasper.ai",
    category: "ai-marketing",
    pricing: "subscription",
    rating: "4.5",
    reviewCount: 1450,
    tags: ["content-writing", "marketing", "brand-voice", "seo", "templates"],
    contactEmail: "contact@jasper.ai",
    featured: false,
    status: "approved"
  },
  {
    name: "Copy.ai",
    shortDescription: "AI copywriter for social media captions, ads, and workflow automation",
    detailedDescription: "Versatile AI writing tool optimized for short-form content including Instagram captions, tweets, ad copy, and email sequences. Features workflow automation, brand kit integration, and specialized templates for different marketing channels.",
    url: "https://copy.ai",
    category: "ai-marketing",
    pricing: "freemium",
    rating: "4.3",
    reviewCount: 720,
    tags: ["copywriting", "social-media", "ad-copy", "automation", "templates"],
    contactEmail: "contact@copy.ai",
    featured: false,
    status: "approved"
  },
  {
    name: "Ocoya",
    shortDescription: "All-in-one AI social media tool with content creation in 26 languages",
    detailedDescription: "Comprehensive social media management platform combining AI content creation, scheduling, analytics, and automation. Supports 26 languages, features graphic design tools, and provides unified management across all major social platforms.",
    url: "https://ocoya.com",
    category: "ai-marketing",
    pricing: "subscription",
    rating: "4.4",
    reviewCount: 380,
    tags: ["multilingual", "social-media", "design", "scheduling", "analytics"],
    contactEmail: "contact@ocoya.com",
    featured: false,
    status: "approved"
  },
  {
    name: "Albert.ai",
    shortDescription: "Self-optimizing AI campaigns across Facebook, Google, and YouTube",
    detailedDescription: "Autonomous AI marketing platform that creates, manages, and optimizes digital advertising campaigns across major platforms. Features real-time bid optimization, audience targeting, creative testing, and performance analytics for enterprise marketing teams.",
    url: "https://albert.ai",
    category: "ai-marketing",
    pricing: "enterprise",
    rating: "4.2",
    reviewCount: 95,
    tags: ["autonomous-campaigns", "optimization", "advertising", "enterprise", "multi-platform"],
    contactEmail: "contact@albert.ai",
    featured: false,
    status: "approved"
  },

  // AI Healthcare & Medical Tools
  {
    name: "Microsoft AI Diagnostic Orchestrator",
    shortDescription: "AI diagnostic tool with 85% accuracy in complex medical cases",
    detailedDescription: "Revolutionary AI diagnostic platform that correctly diagnoses up to 85% of complex medical cases from New England Journal of Medicine, outperforming physicians by 4x. Features sequential diagnosis, cost optimization, and step-by-step medical reasoning.",
    url: "https://microsoft.ai/healthcare",
    category: "ai-healthcare",
    pricing: "enterprise",
    rating: "4.9",
    reviewCount: 45,
    tags: ["medical-diagnosis", "clinical-reasoning", "healthcare", "enterprise", "microsoft"],
    contactEmail: "contact@microsoft.com",
    featured: true,
    status: "approved"
  },
  {
    name: "Ada Health",
    shortDescription: "AI-powered self-diagnostic chatbot for personalized health assessments",
    detailedDescription: "Intelligent health assessment platform that provides personalized symptom analysis and care guidance. Features comprehensive medical knowledge base, symptom checker, and care service direction for millions of users worldwide.",
    url: "https://ada.com",
    category: "ai-healthcare",
    pricing: "freemium",
    rating: "4.4",
    reviewCount: 12000,
    tags: ["symptom-checker", "health-assessment", "chatbot", "personalized", "medical"],
    contactEmail: "contact@ada.com",
    featured: false,
    status: "approved"
  },
  {
    name: "IDx-DR",
    shortDescription: "FDA-approved autonomous AI for diabetic retinopathy detection",
    detailedDescription: "First FDA-approved autonomous AI diagnostic system for detecting diabetic retinopathy in retinal photographs. Provides immediate results without physician interpretation, revolutionizing point-of-care diabetic eye screening.",
    url: "https://eyediagnosis.net",
    category: "ai-healthcare",
    pricing: "enterprise",
    rating: "4.7",
    reviewCount: 180,
    tags: ["fda-approved", "ophthalmology", "diabetic-retinopathy", "autonomous", "medical-imaging"],
    contactEmail: "contact@eyediagnosis.net",
    featured: false,
    status: "approved"
  },
  {
    name: "Viz.ai",
    shortDescription: "Real-time AI stroke detection from CT scans for emergency care",
    detailedDescription: "AI-powered stroke detection platform that analyzes CT scans in real-time to identify large vessel occlusions. Enables faster treatment decisions in emergency settings, potentially saving lives through rapid stroke identification and care coordination.",
    url: "https://viz.ai",
    category: "ai-healthcare",
    pricing: "enterprise",
    rating: "4.6",
    reviewCount: 240,
    tags: ["stroke-detection", "ct-scan", "emergency-care", "real-time", "medical-imaging"],
    contactEmail: "contact@viz.ai",
    featured: false,
    status: "approved"
  }
];

// Additional categories for the schema
export const newCategories = [
  "ai-automation",
  "ai-video-tools", 
  "ai-code-assistants",
  "ai-marketing",
  "ai-healthcare",
  "ai-drug-discovery",
  "ai-finance",
  "ai-education",
  "ai-legal-tech",
  "ai-gaming",
  "ai-real-estate", 
  "ai-agriculture",
  "ai-cybersecurity",
  "productivity"
];