// Fallback data service when external APIs are not available
import { InsertSubmission } from "@shared/schema";

export const fallbackAITools: InsertSubmission[] = [
  {
    name: "OpenAI GPT-4",
    category: "large-language-models",
    url: "https://openai.com/gpt-4",
    pricing: "paid",
    shortDescription: "Advanced AI language model with superior reasoning capabilities",
    detailedDescription: "GPT-4 is OpenAI's most advanced system, producing safer and more useful responses with broader general knowledge and problem solving abilities.",
    tags: ["language-model", "reasoning", "multimodal", "api"],
    contactEmail: "support@openai.com",
    status: "approved" as const,
    rating: "4.8",
    reviewCount: 2500,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Claude by Anthropic",
    category: "large-language-models", 
    url: "https://claude.ai",
    pricing: "freemium",
    shortDescription: "Constitutional AI assistant focused on being helpful, harmless, and honest",
    detailedDescription: "Claude is an AI assistant created by Anthropic using Constitutional AI techniques designed to be helpful, harmless, and honest.",
    tags: ["constitutional-ai", "safety", "reasoning", "analysis"],
    contactEmail: "support@anthropic.com",
    status: "approved" as const,
    rating: "4.7",
    reviewCount: 1800,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Stable Diffusion",
    category: "ai-art-generators",
    url: "https://stability.ai/stable-image",
    pricing: "freemium",
    shortDescription: "Open-source AI image generator for creating stunning artwork",
    detailedDescription: "Stable Diffusion is a state-of-the-art text-to-image model that generates detailed images from text descriptions.",
    tags: ["image-generation", "open-source", "art", "creative"],
    contactEmail: "support@stability.ai",
    status: "approved" as const,
    rating: "4.6",
    reviewCount: 3200,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "GitHub Copilot",
    category: "ai-code-assistants",
    url: "https://github.com/features/copilot",
    pricing: "paid",
    shortDescription: "AI-powered code completion and programming assistant",
    detailedDescription: "GitHub Copilot is an AI programming assistant that helps you write code faster by suggesting whole lines or entire functions.",
    tags: ["code-completion", "programming", "github", "productivity"],
    contactEmail: "support@github.com",
    status: "approved" as const,
    rating: "4.5",
    reviewCount: 5600,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Midjourney",
    category: "ai-art-generators",
    url: "https://midjourney.com",
    pricing: "paid",
    shortDescription: "AI-powered image generation through Discord bot interface",
    detailedDescription: "Midjourney is an independent research lab producing an AI program that creates images from textual descriptions.",
    tags: ["image-generation", "discord", "art", "creative"],
    contactEmail: "support@midjourney.com",
    status: "approved" as const,
    rating: "4.7",
    reviewCount: 4100,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  }
];

// Note: This is a minimal fallback dataset. In production with API keys,
// the system will fetch real-time data from Product Hunt, GitHub, and Hugging Face
console.log("⚠️  Using fallback data - Add API keys for real-time AI tool data");