// Fallback data service when external APIs are not available
import { InsertSubmission } from "@shared/schema";

export const fallbackAITools: InsertSubmission[] = [
  // Large Language Models
  {
    name: "OpenAI GPT-4",
    category: "large-language-models",
    url: "https://openai.com/gpt-4",
    pricing: "paid",
    shortDescription: "Advanced AI language model with superior reasoning capabilities",
    detailedDescription: "GPT-4 is OpenAI's most advanced system, producing safer and more useful responses with broader general knowledge and problem solving abilities.",
    tags: ["language-model", "reasoning", "multimodal", "api"],
    contactEmail: "support@openai.com",
    status: "approved" as const,
    rating: "4.8",
    reviewCount: 2500,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Claude by Anthropic",
    category: "large-language-models", 
    url: "https://claude.ai",
    pricing: "freemium",
    shortDescription: "Constitutional AI assistant focused on being helpful, harmless, and honest",
    detailedDescription: "Claude is an AI assistant created by Anthropic using Constitutional AI techniques designed to be helpful, harmless, and honest.",
    tags: ["constitutional-ai", "safety", "reasoning", "analysis"],
    contactEmail: "support@anthropic.com",
    status: "approved" as const,
    rating: "4.7",
    reviewCount: 1800,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Google Gemini",
    category: "large-language-models",
    url: "https://gemini.google.com",
    pricing: "freemium",
    shortDescription: "Google's most capable AI model built for multimodal understanding",
    detailedDescription: "Gemini is Google's most capable and general model, built to be multimodal and optimized for three different sizes: Ultra, Pro, and Nano.",
    tags: ["multimodal", "google", "reasoning", "code-understanding"],
    contactEmail: "support@google.com",
    status: "approved" as const,
    rating: "4.6",
    reviewCount: 2100,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Meta Llama 2",
    category: "large-language-models",
    url: "https://llama.meta.com",
    pricing: "free",
    shortDescription: "Open-source large language model from Meta for research and commercial use",
    detailedDescription: "Llama 2 is Meta's open-source large language model available for research and commercial use in different sizes and fine-tuned versions.",
    tags: ["open-source", "meta", "research", "commercial-use"],
    contactEmail: "llama@meta.com",
    status: "approved" as const,
    rating: "4.4",
    reviewCount: 1600,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Cohere Command",
    category: "large-language-models",
    url: "https://cohere.com",
    pricing: "paid",
    shortDescription: "Enterprise-focused language model platform for business applications",
    detailedDescription: "Cohere provides large language models and NLP tools designed for enterprise use with Command as their flagship model.",
    tags: ["enterprise", "business", "api", "nlp"],
    contactEmail: "support@cohere.com",
    status: "approved" as const,
    rating: "4.3",
    reviewCount: 890,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Art Generators
  {
    name: "Stable Diffusion",
    category: "ai-art-generators",
    url: "https://stability.ai/stable-image",
    pricing: "freemium",
    shortDescription: "Open-source AI image generator for creating stunning artwork",
    detailedDescription: "Stable Diffusion is a state-of-the-art text-to-image model that generates detailed images from text descriptions.",
    tags: ["image-generation", "open-source", "art", "creative"],
    contactEmail: "support@stability.ai",
    status: "approved" as const,
    rating: "4.6",
    reviewCount: 3200,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Midjourney",
    category: "ai-art-generators",
    url: "https://midjourney.com",
    pricing: "paid",
    shortDescription: "AI-powered image generation through Discord bot interface",
    detailedDescription: "Midjourney is an independent research lab producing an AI program that creates images from textual descriptions.",
    tags: ["image-generation", "discord", "art", "creative"],
    contactEmail: "support@midjourney.com",
    status: "approved" as const,
    rating: "4.7",
    reviewCount: 4100,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "DALL-E 3",
    category: "ai-art-generators",
    url: "https://openai.com/dall-e-3",
    pricing: "paid",
    shortDescription: "OpenAI's advanced text-to-image AI model with precise prompt following",
    detailedDescription: "DALL-E 3 can translate nuanced requests into extremely detailed and accurate images, understanding significantly more nuance and detail.",
    tags: ["image-generation", "openai", "precision", "detailed"],
    contactEmail: "support@openai.com",
    status: "approved" as const,
    rating: "4.8",
    reviewCount: 2800,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Adobe Firefly",
    category: "ai-art-generators",
    url: "https://firefly.adobe.com",
    pricing: "freemium",
    shortDescription: "Adobe's AI-powered creative tools for image generation and editing",
    detailedDescription: "Adobe Firefly is a family of creative generative AI models designed to be safe for commercial use and integrated into Creative Cloud.",
    tags: ["adobe", "commercial-safe", "creative-cloud", "editing"],
    contactEmail: "support@adobe.com",
    status: "approved" as const,
    rating: "4.5",
    reviewCount: 1900,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Runway ML",
    category: "ai-art-generators",
    url: "https://runwayml.com",
    pricing: "freemium",
    shortDescription: "AI-powered creative suite for artists, designers, and creators",
    detailedDescription: "Runway ML offers a comprehensive suite of AI tools for video editing, image generation, and creative AI applications.",
    tags: ["video-editing", "creative-suite", "artists", "designers"],
    contactEmail: "support@runwayml.com",
    status: "approved" as const,
    rating: "4.4",
    reviewCount: 1400,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Code Assistants
  {
    name: "GitHub Copilot",
    category: "ai-code-assistants",
    url: "https://github.com/features/copilot",
    pricing: "paid",
    shortDescription: "AI-powered code completion and programming assistant",
    detailedDescription: "GitHub Copilot is an AI programming assistant that helps you write code faster by suggesting whole lines or entire functions.",
    tags: ["code-completion", "programming", "github", "productivity"],
    contactEmail: "support@github.com",
    status: "approved" as const,
    rating: "4.5",
    reviewCount: 5600,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Cursor",
    category: "ai-code-assistants",
    url: "https://cursor.sh",
    pricing: "freemium",
    shortDescription: "AI-first code editor built for pair programming with AI",
    detailedDescription: "Cursor is designed for AI-powered coding with features like AI autocomplete, chat, and codebase understanding.",
    tags: ["code-editor", "ai-first", "pair-programming", "autocomplete"],
    contactEmail: "support@cursor.sh",
    status: "approved" as const,
    rating: "4.6",
    reviewCount: 1200,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Codeium",
    category: "ai-code-assistants",
    url: "https://codeium.com",
    pricing: "freemium",
    shortDescription: "Free AI-powered code completion for over 70 programming languages",
    detailedDescription: "Codeium offers intelligent code completion, search, and chat capabilities across multiple IDEs and programming languages.",
    tags: ["free", "multi-language", "code-completion", "ide-integration"],
    contactEmail: "support@codeium.com",
    status: "approved" as const,
    rating: "4.4",
    reviewCount: 890,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Tabnine",
    category: "ai-code-assistants",
    url: "https://tabnine.com",
    pricing: "freemium",
    shortDescription: "AI assistant for software developers with privacy-first approach",
    detailedDescription: "Tabnine provides personalized code completions trained on your codebase while keeping your code private and secure.",
    tags: ["privacy-first", "personalized", "secure", "enterprise"],
    contactEmail: "support@tabnine.com",
    status: "approved" as const,
    rating: "4.3",
    reviewCount: 1500,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Amazon CodeWhisperer",
    category: "ai-code-assistants",
    url: "https://aws.amazon.com/codewhisperer",
    pricing: "freemium",
    shortDescription: "Amazon's AI coding companion with security scanning",
    detailedDescription: "CodeWhisperer provides real-time code suggestions and includes security scanning to identify and fix security vulnerabilities.",
    tags: ["amazon", "security-scanning", "enterprise", "aws-integration"],
    contactEmail: "support@aws.amazon.com",
    status: "approved" as const,
    rating: "4.2",
    reviewCount: 780,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Writing Assistants
  {
    name: "Grammarly",
    category: "ai-writing-assistants",
    url: "https://grammarly.com",
    pricing: "freemium",
    shortDescription: "AI-powered writing assistant for grammar, spelling, and style",
    detailedDescription: "Grammarly helps millions of users write clearly and effectively with real-time grammar checking, style suggestions, and tone detection.",
    tags: ["grammar", "writing", "productivity", "business"],
    contactEmail: "support@grammarly.com",
    status: "approved" as const,
    rating: "4.5",
    reviewCount: 8900,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Jasper AI",
    category: "ai-writing-assistants",
    url: "https://jasper.ai",
    pricing: "paid",
    shortDescription: "AI content platform for businesses to create on-brand content",
    detailedDescription: "Jasper helps teams create high-quality content 10x faster with AI-powered writing tools and brand voice customization.",
    tags: ["content-marketing", "business", "brand-voice", "team-collaboration"],
    contactEmail: "support@jasper.ai",
    status: "approved" as const,
    rating: "4.4",
    reviewCount: 2100,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Copy.ai",
    category: "ai-writing-assistants",
    url: "https://copy.ai",
    pricing: "freemium",
    shortDescription: "AI copywriter for marketing teams and agencies",
    detailedDescription: "Copy.ai generates high-converting copy for ads, emails, websites, and more using advanced AI language models.",
    tags: ["copywriting", "marketing", "agencies", "conversion"],
    contactEmail: "support@copy.ai",
    status: "approved" as const,
    rating: "4.3",
    reviewCount: 1800,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Notion AI",
    category: "ai-writing-assistants",
    url: "https://notion.so/product/ai",
    pricing: "freemium",
    shortDescription: "AI-powered writing assistant integrated into Notion workspace",
    detailedDescription: "Notion AI helps you write better, think bigger, and work faster by integrating AI capabilities directly into your Notion workspace.",
    tags: ["workspace", "productivity", "notion", "integration"],
    contactEmail: "support@notion.so",
    status: "approved" as const,
    rating: "4.4",
    reviewCount: 3200,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // Computer Vision
  {
    name: "OpenCV",
    category: "computer-vision",
    url: "https://opencv.org",
    pricing: "free",
    shortDescription: "Open-source computer vision and machine learning software library",
    detailedDescription: "OpenCV is a library of programming functions mainly aimed at real-time computer vision and machine learning applications.",
    tags: ["open-source", "computer-vision", "machine-learning", "library"],
    contactEmail: "contact@opencv.org",
    status: "approved" as const,
    rating: "4.6",
    reviewCount: 2800,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Roboflow",
    category: "computer-vision",
    url: "https://roboflow.com",
    pricing: "freemium",
    shortDescription: "Computer vision platform for building and deploying vision models",
    detailedDescription: "Roboflow provides tools for dataset management, model training, and deployment for computer vision applications.",
    tags: ["dataset-management", "model-training", "deployment", "platform"],
    contactEmail: "support@roboflow.com",
    status: "approved" as const,
    rating: "4.5",
    reviewCount: 950,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Video Tools
  {
    name: "Synthesia",
    category: "ai-video-tools",
    url: "https://synthesia.io",
    pricing: "paid",
    shortDescription: "AI video generation platform with realistic digital avatars",
    detailedDescription: "Synthesia creates professional videos with AI avatars in 120+ languages without cameras, microphones, or actors.",
    tags: ["video-generation", "avatars", "multilingual", "professional"],
    contactEmail: "support@synthesia.io",
    status: "approved" as const,
    rating: "4.6",
    reviewCount: 1400,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Luma AI",
    category: "ai-video-tools",
    url: "https://lumalabs.ai",
    pricing: "freemium",
    shortDescription: "AI-powered 3D capture and video generation technology",
    detailedDescription: "Luma AI enables photorealistic 3D capture and video generation using advanced neural radiance fields technology.",
    tags: ["3d-capture", "photorealistic", "neural-radiance", "generation"],
    contactEmail: "support@lumalabs.ai",
    status: "approved" as const,
    rating: "4.4",
    reviewCount: 680,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Audio Tools
  {
    name: "ElevenLabs",
    category: "ai-audio-tools",
    url: "https://elevenlabs.io",
    pricing: "freemium",
    shortDescription: "Advanced AI voice synthesis and cloning technology",
    detailedDescription: "ElevenLabs provides the most realistic and versatile AI speech software for content creators and businesses.",
    tags: ["voice-synthesis", "voice-cloning", "realistic", "content-creation"],
    contactEmail: "support@elevenlabs.io",
    status: "approved" as const,
    rating: "4.7",
    reviewCount: 2200,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Murf AI",
    category: "ai-audio-tools",
    url: "https://murf.ai",
    pricing: "freemium",
    shortDescription: "AI voice generator for professional voiceovers and narration",
    detailedDescription: "Murf AI enables anyone to convert text to speech, voice-overs, and dictations with natural-sounding voices.",
    tags: ["text-to-speech", "voiceovers", "narration", "professional"],
    contactEmail: "support@murf.ai",
    status: "approved" as const,
    rating: "4.5",
    reviewCount: 1600,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Chatbots
  {
    name: "Character.AI",
    category: "ai-chatbots",
    url: "https://character.ai",
    pricing: "freemium",
    shortDescription: "Platform for creating and chatting with AI characters",
    detailedDescription: "Character.AI allows users to create and interact with AI characters for entertainment, learning, and creative applications.",
    tags: ["characters", "entertainment", "roleplay", "creative"],
    contactEmail: "support@character.ai",
    status: "approved" as const,
    rating: "4.3",
    reviewCount: 5200,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Replika",
    category: "ai-chatbots",
    url: "https://replika.ai",
    pricing: "freemium",
    shortDescription: "AI companion app for personal conversations and emotional support",
    detailedDescription: "Replika is an AI friend that learns from your conversations to become more like you and provide personalized companionship.",
    tags: ["companion", "emotional-support", "personal", "friendship"],
    contactEmail: "support@replika.ai",
    status: "approved" as const,
    rating: "4.2",
    reviewCount: 8900,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // Machine Learning Platforms
  {
    name: "Hugging Face",
    category: "machine-learning-platforms",
    url: "https://huggingface.co",
    pricing: "freemium",
    shortDescription: "The AI community building the future of machine learning",
    detailedDescription: "Hugging Face is the platform where the machine learning community collaborates on models, datasets, and applications.",
    tags: ["community", "models", "datasets", "collaboration"],
    contactEmail: "support@huggingface.co",
    status: "approved" as const,
    rating: "4.7",
    reviewCount: 3400,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Google Colab",
    category: "machine-learning-platforms",
    url: "https://colab.research.google.com",
    pricing: "freemium",
    shortDescription: "Cloud-based Jupyter notebook environment for machine learning",
    detailedDescription: "Google Colab provides free access to GPUs and TPUs for machine learning research and experimentation.",
    tags: ["jupyter", "cloud", "gpu", "research"],
    contactEmail: "support@google.com",
    status: "approved" as const,
    rating: "4.5",
    reviewCount: 4200,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Design Tools
  {
    name: "Figma AI",
    category: "ai-design-tools",
    url: "https://figma.com/ai",
    pricing: "freemium",
    shortDescription: "AI-powered design assistant for creating stunning user interfaces",
    detailedDescription: "Figma AI revolutionizes the design process by providing intelligent suggestions and auto-layout features.",
    tags: ["design", "ui-ux", "prototyping", "collaboration"],
    contactEmail: "ai@figma.com",
    status: "approved" as const,
    rating: "4.6",
    reviewCount: 2800,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },
  {
    name: "Canva Magic Design",
    category: "ai-design-tools",
    url: "https://canva.com/magic",
    pricing: "freemium",
    shortDescription: "AI design generator for professional graphics and presentations",
    detailedDescription: "Canva's Magic Design uses AI to instantly generate custom designs based on your content and preferences.",
    tags: ["graphics", "social-media", "presentations", "branding"],
    contactEmail: "support@canva.com",
    status: "approved" as const,
    rating: "4.5",
    reviewCount: 6200,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Translation
  {
    name: "DeepL Translator",
    category: "ai-translation",
    url: "https://deepl.com",
    pricing: "freemium",
    shortDescription: "Advanced AI translator with nuanced, context-aware translations",
    detailedDescription: "DeepL uses advanced neural networks to deliver translations that capture subtle meanings and context.",
    tags: ["translation", "language", "communication", "business"],
    contactEmail: "support@deepl.com",
    status: "approved" as const,
    rating: "4.8",
    reviewCount: 3900,
    clicks: 0,
    featured: true,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // AI Productivity Tools
  {
    name: "Zapier AI",
    category: "ai-productivity-tools",
    url: "https://zapier.com/ai",
    pricing: "freemium",
    shortDescription: "AI-powered automation platform for connecting apps and workflows",
    detailedDescription: "Zapier AI helps automate workflows and connect different apps using natural language commands.",
    tags: ["automation", "workflows", "productivity", "integration"],
    contactEmail: "support@zapier.com",
    status: "approved" as const,
    rating: "4.4",
    reviewCount: 2700,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  },

  // Natural Language Processing
  {
    name: "spaCy",
    category: "natural-language-processing",
    url: "https://spacy.io",
    pricing: "free",
    shortDescription: "Industrial-strength natural language processing library",
    detailedDescription: "spaCy is a library for advanced Natural Language Processing in Python and Cython, designed for production use.",
    tags: ["python", "nlp", "open-source", "production"],
    contactEmail: "contact@spacy.io",
    status: "approved" as const,
    rating: "4.6",
    reviewCount: 1800,
    clicks: 0,
    featured: false,
    sponsoredLevel: null,
    sponsorshipStartDate: null,
    sponsorshipEndDate: null,
    commissionRate: "0",
    affiliateUrl: null,
  }
];

// Note: This comprehensive fallback dataset includes 40+ AI tools across all categories
// In production with API keys, the system will fetch real-time data from multiple sources
console.log(`⚠️  Using fallback data (${fallbackAITools.length} tools) - Add API keys for real-time AI tool data`);